### ISSUE TITLE
Publish as a node module?

### ISSUE THREAD

**Issue by mapmeld** [yan9a/mcal#1]
Mingalaba!

I worked on the MaePaySoh project in Myanmar in 2015 and have published some modules on npm for converting Myanmar numbers, Zawgyi and WinResearcher encodings, sorting, names, etc.  The Myanmar calendar was something which was actually difficult for us to work around.  I'm psyched to see that there is now a JS library!

Would you be interested in making this a node module? Otherwise I can adapt it from your code here

**Comment by yan9a** [comment]
Thanks for the info. I am not interested in making node module. You can adapt it from the code here.
