### ISSUE TITLE
Adding C++ code to Unicode/ICU

### ISSUE THREAD

**Issue by mapmeld** [yan9a/mcal#2]
Mingalaba,

I am trying to add the Burmese calendar to Unicode / ICU / CLDR
https://github.com/unicode-org/icu

Your C++ Code is open source, so I intend to use it in the module. But you are still the main author.

Would you sign the Contributor License Agreement (CLA) for Unicode? https://cla-assistant.io/unicode-org/icu ? Please let me know if you have questions.

You can see my progress at https://github.com/Georeactor/icu/blob/buddhist-hack/icu4c/source/i18n/buddhcal.cpp

Thanks!

**Comment by yan9a** [comment]
Hi @mapmeld,
Thanks for the effort to add the Burmese calendar to Unicode. I just signed the CLA. 
Cheer!

**Comment by mapmeld** [comment]
great! I will revisit this soon
